# Generated by Django 6.1 on 2026-09-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_servicecategory_servicerequest_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='service.servicecategory'),
        ),
    ]
