# Generated by Django 6.1 on 2026-09-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_technician_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='email',
        ),
    ]
